robot:
  last_task_id: 3
  total_robot_num: 1
mysql:
  ip: b'\x1dw\x93\xa0\xf2\x1a\xb3\xf2\xfd1T\x11y'
  password: b'\xa0\xef\xe0\xe5'
security:
  ip_tag: b'\xb7\x13\xe3\x16".E\x17:\xf5\xbf\x06\xb6\xef\xa0k'
  password_tag: b'n\xe5\x8f\x9c\x93\xb3\xc0\xc5K\xc7\xbd\xe1\xbf\xf2\xf3:'